---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asynqmon
  labels:
    app: asynqmon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asynqmon
  template:
    metadata:
      labels:
        app: asynqmon
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - asynqmon
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: asynqmon
          image: x
          env:
            - name: REDIS_ADDR
              value: redis.default.svc.cluster.local:6379
            - name: REDIS_PASSWORD
              value: xxx
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: asynqmon
  labels:
    app: asynqmon
spec:
  type: NodePort
  ports:
    - name: asynqmon
      port: 8080
      targetPort: 8080
      nodePort: 31000
  selector:
    app: asynqmon