---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - groot-scheduler
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: scheduler
          image: xxx
          env:
            - name: CONF_ENV
              value: "dev"
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
#          livenessProbe:
#            tcpSocket:
#              port: 80
#            initialDelaySeconds: 5
#            timeoutSeconds: 1
#            periodSeconds: 10
#            successThreshold: 1
#            failureThreshold: 3
#          readinessProbe:
#            tcpSocket:
#              port: 80
#            initialDelaySeconds: 5
#            timeoutSeconds: 1
#            periodSeconds: 10
#            successThreshold: 1
#            failureThreshold: 3
          volumeMounts:
            - mountPath: /opt/conf/conf.yaml
              name: config
              subPath: conf.yaml
      volumes:
        - name: config
          configMap:
            name: config