---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - server
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: server
          image: xxx
          ports:
            - containerPort: 80
          env:
            - name: CONF_ENV
              value: "dev"
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: /opt/conf/conf.yaml
              name: config
              subPath: conf.yaml
      volumes:
        - name: config
          configMap:
            name: config

---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  type: NodePort
  ports:
    - name: server
      port: 80
      targetPort: 80
      nodePort: 31001
  selector:
    app: server