---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - worker
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: worker
          image: x
          env:
            - name: CONF_ENV
              value: "dev"
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
#          livenessProbe:
#            tcpSocket:
#              port: 80
#            initialDelaySeconds: 5
#            timeoutSeconds: 1
#            periodSeconds: 10
#            successThreshold: 1
#            failureThreshold: 3
#          readinessProbe:
#            tcpSocket:
#              port: 80
#            initialDelaySeconds: 5
#            timeoutSeconds: 1
#            periodSeconds: 10
#            successThreshold: 1
#            failureThreshold: 3
          volumeMounts:
            - mountPath: /opt/conf/conf.yaml
              name: config
              subPath: prod.yaml
      volumes:
        - name: config
          configMap:
            name: config